services:
  auth-api:
    build: './auth-api'
    container_name: auth-api
    ports:
      - 8080:8080
    environment:
      - PORT=8080

  auth-db:
    image: postgres:latest
    container_name: auth-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456

  product_api:
    build: './product-api'
    container_name: product-api
    environment:
      - PORT=8081
    ports:
      - 8081:8081

  product-db:
    image: postgres:latest
    container_name: product-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456

  sales_api:
    build: './sales-api'
    container_name: sales-api
    environment:
      - PORT=8082
    ports:
      - 8082:8082

  sales_db:
    image: mongo
    container_name: sales-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456

  sales_rabbitmq:
    image: rabbitmq:3-management
    container_name: sales-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
